services:
  primes:
    build:
      context: .
      dockerfile: ops/dbDockfile/Dockerfile
    container_name: primes
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED="true"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db-primes
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5342:5342

  nginx:
    image: 'nginx@sha256:e9293c9bedb0db866e7d2b69e58131db4c2478e6cd216cdd99b134830703983a'
    container_name: nginx_cn1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt

  frontend:
    image: primes-frontend
    pull_policy: never
    container_name: primes-frontend
    build:
        context: .
        dockerfile: ops/frontDockfile/Dockerfile
    ports:
      - 80:80