services:
  projectp:
    build:
      context: .
      dockerfile: ops/dbDockfile/Dockerfile
    container_name: primes
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED="true"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db-primes
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5342:5342